env:
  es6: true
  node: true
  jest: true
extends: 'airbnb-base'
parserOptions:
  sourceType: module
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
  quote-props:
    - error
    - consistent-as-needed
  default-case:
    - warn
  no-else-return:
    - warn
  no-console:
    - off
  require-jsdoc: 0
